// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8-qzL05jFni9r8p-016BlIdJVQ2vkpn8',
    appId: '1:800489858716:web:36d99ed8f336de654e6f59',
    messagingSenderId: '800489858716',
    projectId: 'todo-66023',
    authDomain: 'todo-66023.firebaseapp.com',
    databaseURL: 'https://todo-66023-default-rtdb.firebaseio.com',
    storageBucket: 'todo-66023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb19ptVnMj5lz-Gy27kdTnQrysOTjsfps',
    appId: '1:800489858716:android:e1b123c1fce22ace4e6f59',
    messagingSenderId: '800489858716',
    projectId: 'todo-66023',
    databaseURL: 'https://todo-66023-default-rtdb.firebaseio.com',
    storageBucket: 'todo-66023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBDeE7UoZnLtYEMsseNb9OKc0KsHF9p84',
    appId: '1:800489858716:ios:657554d5d4e93a9f4e6f59',
    messagingSenderId: '800489858716',
    projectId: 'todo-66023',
    databaseURL: 'https://todo-66023-default-rtdb.firebaseio.com',
    storageBucket: 'todo-66023.appspot.com',
    iosClientId: '800489858716-tivvkral6v89os39teu4bo2a7ejfggm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
